{
  "vid": "d9dbe6e8-84da-11e3-98bd-080027f2d077",
  "topic": "varnish -- DoS vulnerability in Varnish HTTP cache",
  "affects": [
    {
      "name": [
        "varnish"
      ],
      "range": [
        {
          "lt": "3.0.5"
        }
      ]
    }
  ],
  "description": {
    "xmlns": "http://www.w3.org/1999/xhtml",
    "text": "\n\t<p>Varnish Cache Project reports:</p>\n\t<blockquote cite=\"https://www.varnish-cache.org/lists/pipermail/varnish-announce/2013-October/000686.html\">\n\t  <p>If Varnish receives a certain illegal request, and the subroutine\n\t    'vcl_error{}' restarts the request, the varnishd worker process\n\t    will crash with an assert.\n\t  </p>\n\t  <p>The varnishd management process will restart the worker process, but\n\t    there will be a brief interruption of service and the cache will be\n\t    emptied, causing more traffic to go to the backend.\n\t  </p>\n\t  <p>We are releasing this advisory because restarting from vcl_error{} is\n\t    both fairly common and documented.</p>\n\t  <p>This is purely a denial of service vulnerability, there is no risk of\n\t    privilege escalation.</p>\n\t  <p>Workaround</p>\n\t  <p>Insert this at the top of your VCL file:</p>\n\t  <pre>\n\t\tsub vcl_error {\n\t\t\tif (obj.status == 400 || obj.status == 413) {\n\t\t\t\treturn(deliver);\n\t\t\t}\n\t\t}\n\n\t\tOr add this test at the top of your existing vcl_error{}.\n\t  </pre>\n\t</blockquote>\n      "
  },
  "references": {
    "cvename": [
      "CVE-2013-4484"
    ],
    "mlist": [
      {
        "text": "https://www.varnish-cache.org/lists/pipermail/varnish-announce/2013-October/000686.html"
      }
    ]
  },
  "dates": {
    "discovery": "2013-10-30",
    "entry": "2014-01-25"
  }
}
